#!/usr/bin/env python3
"""Generate the ``.inx`` files and install the add-in into Inkscape.

Inkscape learns about an extension from an ``.inx`` - an XML file naming the menu entry, the
script to run and the arguments to pass it. One per command, and they differ only in the label and
the ``--command`` value, so they are generated from the table below rather than maintained by
hand: twenty hand-written near-copies is how one of them quietly stops matching the others.

    python build.py            # write the .inx files next to nexus_plm.py
    python build.py --install  # ...and copy everything into the user's extensions directory

No third-party packages: this runs on whatever Python is to hand, including Inkscape's own.
"""

import argparse
import os
import shutil
import sys
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))

#: The submenu every entry appears under: Extensions ▸ Nexus PLM ▸ …
SUBMENU = "Nexus PLM"

#: Reverse-DNS prefix for the extension ids. Inkscape requires each id to be unique across every
#: installed extension, and silently ignores the second of a duplicate pair.
ID_PREFIX = "com.nexusplm.inkscape"

#: Every menu entry: the command name the script dispatches on, and the label the user reads.
#:
#: Inkscape sorts the entries in a submenu itself, so the order here is documentation rather than
#: presentation - it is grouped the way the other Nexus add-ins group their toolbars so that a
#: reader can see the command set is the same one.
MENU = [
    # Account
    ("sign-in",           "Sign In..."),
    ("sign-out",          "Sign Out"),
    # Data management
    ("new-from-template", "New from Template..."),
    ("open-from-plm",     "Open from PLM..."),
    ("search",            "Search..."),
    ("save-to-plm",       "Save to PLM"),
    ("save-as-new",       "Save As New Item..."),
    ("save-as-existing",  "Save As Existing Item..."),
    # Lifecycle
    ("check-out",         "Check Out"),
    ("check-in",          "Check In"),
    ("revise",            "Revise"),
    ("change-owner",      "Change Ownership..."),
    # Workflow
    ("worklist",          "My Worklist..."),
    ("new-workflow",      "New Workflow..."),
    # Attributes
    ("properties",        "Properties..."),
    ("edit-values",       "Edit Values..."),
    ("refresh-values",    "Refresh Values"),
    # Information
    ("settings",          "Current Settings..."),
    ("connection-status", "Connection Status"),
    ("help",              "Help"),
    ("about",             "About"),
]

#: The package and the entry point, copied together on install.
PAYLOAD = ["nexus_plm.py", "nexusplm"]

TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build.py. Do not edit: your change will be overwritten. -->
<inkscape-extension xmlns="http://www.inkscape.org/namespace/inkscape/extension">
    <name>{label}</name>
    <id>{extension_id}</id>
    <param name="command" type="string" gui-hidden="true">{command}</param>
    <effect needs-live-preview="false">
        <object-type>all</object-type>
        <effects-menu>
            <submenu name="{submenu}"/>
        </effects-menu>
    </effect>
    <script>
        <command location="inx" interpreter="python">nexus_plm.py</command>
    </script>
</inkscape-extension>
"""

# Every entry needs a document, and that is not an oversight.
#
# The obvious thing is `needs-document="false"` on the commands that are about PLM rather than
# about this drawing - Sign In, Open from PLM, My Worklist. It does not work, and it fails in a
# way that looks like the add-in is broken. Measured on Inkscape 1.4.2: run an EffectExtension
# with no document and inkex dies inside its own loader before the extension's code is reached -
#
#     File "...inkex/base.py", line 504, in load
#       self.svg.selection.set(*self.options.ids)
#     AttributeError: 'NoneType' object has no attribute 'selection'
#
# - and Inkscape shows that traceback to the user. An EffectExtension is defined as something that
# acts on a document; there is no supported way to have one without.
#
# The cost is nearly nothing, which is what settles it: Inkscape closes the window with the last
# document, so "Inkscape running with no document open" is a state a person can barely reach.


def inx_name(command):
    """The file name for a command's ``.inx``: ``nexus_plm_sign_in.inx``."""
    return "nexus_plm_%s.inx" % command.replace("-", "_")


def write_inx(directory=HERE):
    """Write one ``.inx`` per menu entry. Returns the paths written."""
    written = []
    for command, label in MENU:
        path = os.path.join(directory, inx_name(command))
        body = TEMPLATE.format(
            label=escape(label),
            extension_id="%s.%s" % (ID_PREFIX, command),
            command=escape(command),
            submenu=escape(SUBMENU),
        )
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        written.append(path)
    return written


def user_extensions_dir():
    """Where Inkscape looks for a user's own extensions, per platform."""
    if sys.platform == "win32":
        base = os.environ.get("APPDATA") or os.path.expanduser("~")
        return os.path.join(base, "inkscape", "extensions")
    if sys.platform == "darwin":
        return os.path.expanduser("~/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions")
    return os.path.expanduser("~/.config/inkscape/extensions")


def install(target=None):
    """Copy the add-in into Inkscape's user extensions directory."""
    target = target or user_extensions_dir()
    os.makedirs(target, exist_ok=True)

    for name in PAYLOAD:
        source = os.path.join(HERE, name)
        destination = os.path.join(target, name)
        if os.path.isdir(source):
            # Replace rather than merge: a module deleted from the source must not survive in the
            # installed copy, which is how a stale file goes on being imported for weeks.
            shutil.rmtree(destination, ignore_errors=True)
            shutil.copytree(source, destination,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        else:
            shutil.copy2(source, destination)

    for command, _label in MENU:
        name = inx_name(command)
        shutil.copy2(os.path.join(HERE, name), os.path.join(target, name))

    return target


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", action="store_true",
                        help="also copy the add-in into Inkscape's user extensions directory")
    parser.add_argument("--target", help="install somewhere other than the default")
    arguments = parser.parse_args()

    written = write_inx()
    print("wrote %d .inx file(s)" % len(written))

    if arguments.install:
        target = install(arguments.target)
        print("installed to %s" % target)


if __name__ == "__main__":
    main()
