; Inno Setup script for the Nexus PLM extension for Inkscape.
;
; There is no build step. The extension is Python that runs under Inkscape's own interpreter, so
; what ships is what is in `extension\` - the entry point, the package, and the generated .inx
; files. Compile it with:
;
;   "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" installer\Nexus.PLM.Inkscape.Addin.iss
;
; PER-USER, NO ELEVATION. Inkscape reads extensions from two places: one under Program Files,
; which needs admin rights and is wiped by the next Inkscape update, and one under
; %APPDATA%\inkscape\extensions, which needs neither. This installs into the second.
;
; WHAT THIS DOES NOT INSTALL: the Nexus PLM tray application, which hosts the Addin Service the
; extension talks to on localhost. It comes from Nexus.PLM.WPF.Addins. Two installers writing the
; same files is how one of them silently wins, and the extension says plainly when the service is
; not running.
;
; `tests\test_installer.py` holds this file against the source: the version here against
; nexusplm.commands.VERSION, the destination against build.py's, and every payload item against
; what is really in extension\. Nothing about getting those wrong fails loudly.

#define AppName "Nexus PLM for Inkscape"
#define AppPublisher "NexusPLM"

; Keep in step with extension\nexusplm\commands.py VERSION. tests\test_installer.py fails when
; they drift.
#define AppVersion "0.2.0"

; Inkscape's per-user extension directory. Roaming, not Local: Inkscape keeps its whole profile
; under %APPDATA%, and that is where build.py installs to as well.
#define ExtensionsDir "{userappdata}\inkscape\extensions"

[Setup]
AppId={{B4E1F7C3-2A9D-4E56-9C7B-1F3A8D6E2B90}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
; Nothing is installed here - the extension goes into Inkscape's own folder - but Inno wants an
; application directory for its uninstall record, so it gets one it will not fill.
DefaultDirName={localappdata}\Programs\Nexus PLM Inkscape Addin
DefaultGroupName=Nexus PLM
DisableProgramGroupPage=yes
DisableDirPage=yes
PrivilegesRequired=lowest
OutputBaseFilename=NexusPlmInkscapeAddinSetup
OutputDir=Output
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#AppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; The entry point every .inx runs.
Source: "..\extension\nexus_plm.py"; DestDir: "{#ExtensionsDir}"; Flags: ignoreversion
; The package. __pycache__ is excluded because a stale compiled file is how an old module goes
; on being imported after its source has changed.
Source: "..\extension\nexusplm\*"; DestDir: "{#ExtensionsDir}\nexusplm"; \
  Excludes: "__pycache__,*.pyc"; Flags: recursesubdirs createallsubdirs ignoreversion
; One .inx per menu entry, generated by build.py from its MENU table.
Source: "..\extension\nexus_plm_*.inx"; DestDir: "{#ExtensionsDir}"; Flags: ignoreversion

[UninstallDelete]
; Only what this installed. The extensions directory holds every other extension the user has.
Type: filesandordirs; Name: "{#ExtensionsDir}\nexusplm"
Type: files; Name: "{#ExtensionsDir}\nexus_plm.py"
Type: files; Name: "{#ExtensionsDir}\nexus_plm_*.inx"

[Code]

// Inkscape creates its profile on first run. Absent, either Inkscape is not installed or it has
// never been started - and an extension dropped into a folder nothing reads looks like a failed
// install with no error. Warn, and let the user decide: installing Inkscape afterwards and
// starting it picks the extension up, so this is a caution rather than a refusal.
function InitializeSetup(): Boolean;
begin
  Result := True;
  if not DirExists(ExpandConstant('{userappdata}\inkscape')) then
    Result := MsgBox(
      'Inkscape was not found for this user.' + #13#10#13#10 +
      'Its profile folder does not exist yet, which means it is either not installed or has ' +
      'never been started. The extension can still be installed now and will appear the first ' +
      'time Inkscape runs.' + #13#10#13#10 +
      'Continue?',
      mbConfirmation, MB_YESNO) = IDYES;
end;

// Inkscape reads the .inx files when it starts. Installing underneath a running Inkscape leaves
// the user looking at an Extensions menu with no Nexus PLM in it, and concluding the installer
// failed. Inno's CloseApplications cannot help here - Inkscape holds none of these files open -
// so it is said in words instead.
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and (not WizardSilent) then
    MsgBox('Nexus PLM is installed.' + #13#10#13#10 +
           'If Inkscape is open, close it and start it again - it reads its extensions at ' +
           'startup. The commands are under Extensions > Nexus PLM.',
           mbInformation, MB_OK);
end;
